name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Unit and binary tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run unit and binary tests
        run: cargo test --locked --lib --bins

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Test cas with cascli
        run: cargo test --locked --test cas_cli_e2e
      - name: Run cfs end-to-end tests
        run: cargo test --locked --features test-utils --test e2e
